import Head from "next/head";
import { Inter } from "next/font/google";
import Footer from "@/components/footer";
import Input from "@/components/input";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Miss You</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <script async defer data-website-id="0ead285e-df64-469b-85b5-d2e55c7d6a30" src="https://umami.lanceross.me/umami.js"></script>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-col items-center min-h-screen justify-center relative">
        <h1 className="text-3xl sm:text-4xl font-bold">Miss You</h1>
        <p className="max-w-md md:max-w-2xl text-lg px-4 pt-10 pb-10 lg:pb-10 text-center">A simple Next.js app where you can generate a confession and short message to someone you love.</p>
        <div className="max-w-md md:max-w-2xl text-lg px-4 text-center">
          <p>Just enter their name on the link of someone you love and you can pick if you want to confess or just tell him or her that you miss them.</p>
          <Input />
        </div>
        <Footer author="Lance Ross" twitter="lancerossdev" />
      </div>
    </>
  );
}
